# Github Actions configuration
name: CI

permissions: {}

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master and ci branches
  push:
    branches:
      - master
      - ci
    paths-ignore:
      - '.appveyor.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.appveyor.yml'

env:
  MAKEFLAGS: -j 4

jobs:
  freebsd:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: cpa.sh {0}
    strategy:
      fail-fast: false
      matrix:
        osver: ['13.5', '14.3', '15.1']
        arch: ['x86_64', 'aarch64']
        gtk: [3]
        build:
          - cc: cc
            cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3 -DENABLE_NLS=1
            cxx: c++
            ldflags: -O3 -lintl
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: start VM
        uses: cross-platform-actions/action@v1
        with:
          operating_system: 'freebsd'
          version: ${{ matrix.osver }}
          architecture: ${{ matrix.arch }}
      - name: install deps
        run: sudo pkg install -y pkgconf docbook-xsl exiv2 libxml2 gtk"${{ matrix.gtk }}" libxslt gettext-tools desktop-file-utils gmake
      - name: build
        run: make -j 3 CC="${{ matrix.build.cc }}" CXX="${{ matrix.build.cxx }}" CFLAGS="${{ matrix.build.cflags }}" LDFLAGS="${{ matrix.build.ldflags }}" GTK="${{ matrix.gtk }}"
      - name: smoke test
        run: ./gpscorrelate -V
      - name: test
        run: make check CHECK_OPTIONS=-v
      - name: install test
        run: |
          make prefix= DESTDIR="${PWD}" install install-desktop-file
          gmake prefix= DESTDIR="${PWD}" install-po
          ls -l bin/gpscorrelate share/locale/de/LC_MESSAGES/gpscorrelate.mo share/applications/gpscorrelate.desktop
